### PR TITLE
rename .txt files to .md files since they are all markdown

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by syvanen** [comment]
Reason for the `.txt` ending is the Jenkins shared library's directory structures: https://jenkins.io/doc/book/pipeline/shared-libraries/#directory-structure

The file extension has to be `.txt` even if the content is Markdown, HTML or any other format. https://groups.google.com/forum/#!topic/jenkinsci-users/w2NA1_JyHSw

**Comment by itewk** [comment]
that is obnoxious

**Comment by syvanen** [comment]
I agree but if we want to have any kind of help inside Jenkins we have to follow this naming convention unfortunately. :(
I think I'll add a README.md that explains the naming convention used in this directory to explain limitation.

**Comment by itewk** [comment]
understood. i just had to vent.

**Pull request closed without merging**
