### PR TITLE
Disabled imageMirror test due to it requiring docker

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
As per comment here:
- https://github.com/redhat-cop/pipeline-library/pull/116#issuecomment-669293861

Have disabled the image mirror test for CI

#### How do we test this?
CI should go green.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by pabrahamsson — APPROVED** [review]
LGTM @garethahealy

**Comment by garethahealy** [comment]
@pabrahamsson ; you good to merge?

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Comment by garethahealy** [comment]
@pabrahamsson ; cant see logs. any ideas why its failing?

**Comment by pabrahamsson** [comment]
> @pabrahamsson ; cant see logs. any ideas why its failing?

The builds that are using the [cakephp-mysql.json](https://raw.githubusercontent.com/openshift/origin/v3.11.0/examples/quickstarts/cakephp-mysql.json) quickstart are failing because the default php version of `7.1` is not available in newer versions of OpenSHift. The quickstart is also using `mysql:5.7` which also is not available.
The PHP version can be set fixed with `-p PHP_VERSION=7.3` but the mysql tag/version isn't parameterized.
I looked at the `release-4.7` version of the quickstart but it has the same issue, I'm suspecting these quickstarts aren't maintained much.

There might also be an issue with Sonarqube static analysis but I haven't had time to dig into that one yet.

**Comment by pabrahamsson** [comment]
@garethahealy as mentioned above there's an issue with our Sonarqube quickstart (incompatible plugin versions). I've submitted a PR to fix this: https://github.com/redhat-cop/containers-quickstarts/pull/459
I've also got a PR almost ready for fixing up the `cakephp-mysql` quickstarts used throughout this repo.

I think we can merge this PR as is unless you prefer for the above to get submitted and merged in first?

**Comment by garethahealy** [comment]
@pabrahamsson ; yep, am fine with merging as-is.

**Pull request merged**
