### PR TITLE
Migrated to github actions

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Removed travis, added github actions

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
`TASK [/tmp/ansible.RjJVOX/pipeline-library/roles/process-tests : Update pipeline-library with correct git branch] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Path /tmp/garethahealy/pipeline-library/dfde40a0302250b04b90625200698298d3249fc7/test/create-pipeline-library.groovy does not exist !", "rc": 257}`

**Comment by pabrahamsson** [comment]
I'm going to have to dig into this one @garethahealy not entirely sure what's going on.

**Comment by etsauer** [comment]
@garethahealy @pabrahamsson it looks like it was a git clone issue... i'm going to try kicking it off again.

**Comment by etsauer** [comment]
@garethahealy @pabrahamsson so, the real failure seems to be at the beginning of the build, before the applier run. It appears to be getting a bad reference to clone:

```
Cloning into '/tmp/garethahealy/pipeline-library/9b83bcf4c3ec59e23145e08903025a1d4f06310b'...
warning: Could not find remote branch 9b83bcf4c3ec59e23145e08903025a1d4f06310b to clone.
fatal: Remote branch 9b83bcf4c3ec59e23145e08903025a1d4f06310b not found in upstream origin
Unexpected end of command stream
9b83bcf4c3ec59e23145e08903025a1d4f06310b
garethahealy/pipeline-library
```
So its getting a branch name of `9b83bcf4c3ec59e23145e08903025a1d4f06310b` instead of `master`

**Comment by etsauer** [comment]
@garethahealy could you try updating `_test/setup.sh`, replacing the `clone()` function with the following:

```
clone() {
  rm -rf ${CLONE_DIR}
  git clone "https://github.com/${CI_REPO_SLUG}.git" ${CLONE_DIR}
  git checkout ${CI_BRANCH}
}
```

**Pull request merged**
