### PR TITLE
binaryBuild - update to allow running against remote cluster and to make parameter names more clear

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by itewk** [comment]
@etsauer broke this off of https://github.com/redhat-cop/pipeline-library/pull/43 since I took the suggestion to merge `buildBinaryFromFile` with `buildBinary` and that other PR is all about adding new functions and this is a breaking change since it standardizes the parameter names.

**Comment by itewk** [comment]
thank you.

**Comment by Gl4di4torRr** [comment]
@itewk sweet. I wanted to do something like this the other day. We ran into limitations as well.

**Comment by itewk** [comment]
@Gl4di4torRr glad to here. I think https://github.com/redhat-cop/pipeline-library/issues/35 may still be an issue but my cluster is currently down so I can't test. I would be curious to here if you have an issue with the `.logs('-f')` call or not.

**Pull request merged**
