### PR TITLE
Update verify to look at dc rollout status

### LINKED ISSUE #95: Intermittent infinite loop in verifyDeployment
https://github.com/redhat-cop/pipeline-library/blob/master/vars/verifyDeployment.groovy#L29:L60

It appears this takes a look at one "podSelector list" in time that may not have the pods we are looking to watch, and hence gets stuck in an infinite loop.

### PR DESCRIPTION
**Pull request by kkoller**
Use native k8 definition of successful rollout instead of parsing pod status.  

fixes #95

#### What is this PR About?
Use native k8 definition of successful rollout instead of parsing pod status.

#### How do we test this?
Reference this shared library, rollout any new deployment, and call the verifyDeployment function against that deployment

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
rollout already kinda does this - the only bit which is "missing" is rollout forces latest but i've got a PR planned to make that optional.
- https://github.com/redhat-cop/pipeline-library/blob/master/vars/rollout.groovy

Do we want 2 methods doing the same? or push everyone to use 1 method?

**Comment by kkoller** [comment]
> rollout already kinda does this - the only bit which is "missing" is rollout forces latest but i've got a PR planned to make that optional.
> 
> * https://github.com/redhat-cop/pipeline-library/blob/master/vars/rollout.groovy
> 
> Do we want 2 methods doing the same? or push everyone to use 1 method?

I think its a question of whether we want to be opinionated about using 'rollout' to trigger your deployment.  I'm actually a fan of explicitly deploying and not relying on triggers, but lots of people do in fact rely on triggers to deploy.  This method can be called to verify those without triggering a new deployment.

**Comment by briantward** [comment]
Agree with kkoller, something else could cause the rollout.  For example in the current Jenkinsfile examples in container-pipelines, there are image tags that trigger rollouts.  

Also, maybe you should set the timeout based on the value already present in the DC? jsonpath={.spec.strategy.recreateParams.timeoutSeconds}

**Comment by kkoller** [comment]
I defaulted it to just 'higher than the kubernetes default' for a dc, which is 10 mins.  I think in general we'd prefer to see the message that the DC failed progressing, not that our verify timed out.  Also, we'd need to distinguish between rolling and recreate strategy when checking that.

**Comment by kkoller** [comment]
Actually I think I just talked myself into removing the timeout from this function altogether, as its redundant given the configurable timeout at the dc level.

**Comment by kkoller** [comment]
I removed the timeout and shamelessly copied Gareth's additional logging statements.

**Comment by briantward** [comment]
Hmm.  Makes me wonder if we can just overload Gareth's rollout to only perform the actual rollout on request, or to only verify on request.  And here in verifyDeployment, call that one, to prevent the existing verifyDeployment calls from breaking until those calls are refactored.

**Comment by garethahealy** [comment]
@kkoller ; since you are following what is done in the rollout.groovy, i think it would be better to just call that method inside of verifyDeployment.groovy, i.e.:

```
def call(ClusterInput input) {
    assert input.targetApp?.trim(): "Param targetApp should be defined."

    openshift.loglevel(input.loglevel)

    if (input.clusterUrl?.trim().length() > 0) {
        error "clusterUrl is deprecated and will be removed in the next release. Please use 'clusterAPI'"
    }

    rollout([
        clusterAPI         : input.clusterAPI,
        clusterToken       : input.clusterToken,
        projectName        : input.projectName,
        resourceKindAndName: "dc/${input.targetApp}",
        latest             : false
    ])
}
```

**Comment by pabrahamsson** [comment]
@kkoller & @briantward are you guys good with the suggestion from @garethahealy?
I'm hoping we can get this PR sorted and merged as we're running into #95 with our automated testing.

**Comment by garethahealy** [comment]
fyi: needs a rebase to pickup testing PRs

**Comment by briantward** [comment]
@garethahealy @pabrahamsson 

Apologies for the delayed response, but does this line when set to false, not trigger the rollout? So in essence, we are only looking for the rollout status.
https://github.com/redhat-cop/pipeline-library/blob/master/vars/rollout.groovy#L40

I'm assuming but haven't checked or tested myself.  If that's the case, I agree with the last suggestion above by Gareth.

@kkoller can update this if so, or we can submit another PR if he is still OOO...

**Comment by pabrahamsson** [comment]
Thank you for the update @kkoller 
Can you please take a look at a sync/rebase of your branch as it appears to be out of sync with master?

**Comment by kkoller** [comment]
I've rebased from master and made this change.  As this function is now fully superseded by the rollout function, I've also added a deprecation notice.  By the way, it doesn't look like the @deprecated annotation works in the pipeline, does anybody know of a more 'official' way to deprecate a function other than a message in the logs?

**Comment by kkoller** [comment]
> Thank you for the update @kkoller
> Can you please take a look at a sync/rebase of your branch as it appears to be out of sync with master?

@pabrahamsson I had to wrestle with git this morning (brain foggy from holidays I suppose) but this has been updated!

**Comment by briantward** [comment]
@kkoller not sure how you went about your rebase, but at least you only have 2 files out of sync now, with only the right changes needed.  But you have 22 commits to get there. That will be terribly misleading in the commit history when researching past work.  Can you squash them? Or just start over a new branch from master and cherry-pick the latest commits you need from this branch and force update remote?

**Comment by etsauer** [comment]
@briantward we squash all commits automatically on merge, so that won't be an issue.

**Comment by briantward** [comment]
@etsauer sweet.  I do remember that now.  Thanks.

lgtm

**Comment by kkoller** [comment]
> @kkoller not sure how you went about your rebase, but at least you only have 2 files out of sync now, with only the right changes needed. But you have 22 commits to get there. That will be terribly misleading in the commit history when researching past work. Can you squash them? Or just start over a new branch from master and cherry-pick the latest commits you need from this branch and force update remote?

@briantward Amusingly, those commits are not due to the rebase but just my iterating on the solution.  Have to check in the changes to be able to pull them in a pipeline and test them :)

**Comment by garethahealy** [comment]
@kkoller ; since you've added a deprecation noticed in the code, can you add it to the docs file as well please.
- https://github.com/redhat-cop/pipeline-library/blob/master/vars/verifyDeployment.txt

Once thats done, happy to merge.

**Comment by kkoller** [comment]
@garethahealy I updated the docs to include a deprecation notice.

**Pull request merged**
