### PR TITLE
Updated build status badge from travis to gh actions

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
As subject.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
confused as to why its currently failing... since the line it complains about "git clone --single-branch --branch" doesn't exist in the code anymore - unless i did a bad push

**Comment by pabrahamsson** [comment]
> confused as to why its currently failing... since the line it complains about "git clone --single-branch --branch" doesn't exist in the code anymore - unless i did a bad push

I think I know why this is failing @garethahealy, but I'm also not sure I fully understand everything going on in `_test/setup.sh`.
Basically because this PR is not from a fork, Prow is passing the wrong parameters to the `./_test/setup.sh` script.
`CI_REPO_SLUG` gets set to `garethahealy/pipeline-library` but should be `redhat-cop/pipeline-library` (bad assumption on my part). This means we end up with your fork in `CLONE_DIR` and your fork still has the [old way of cloning](https://github.com/garethahealy/pipeline-library/blob/master/roles/process-tests/tasks/main.yml#L23-L28).
I believe we need to coordinate a bit on assumptions and what parameters Prow is passing to the script.

**Pull request closed without merging**
