### PR TITLE
Rollback

### PR DESCRIPTION
**Pull request by Gl4di4torRr**
Adds rollback functionality so we can rollback to the latest successful deployment or a specific revision.

### CODE REVIEW

**Comment by Gl4di4torRr** [comment]
@etsauer who are the appropriate reviewers for this repo?

**Comment by Gl4di4torRr** [comment]
@syvanen sounds good. enjoy PTO :)

**Comment by etsauer** [comment]
@Gl4di4torRr could you add a test directory so that we can more easily review this PR? Something that looks like this: https://github.com/redhat-cop/pipeline-library/tree/master/test/org/redhatcop/util

**Comment by Gl4di4torRr** [comment]
@etsauer @syvanen added some testing... not sure if it's exactly how you want the structure. But I have a simple Jenkinsfile that does a deployment and rollback. Just follow the README to run applier.

**Comment by syvanen** [comment]
The tests worked but I noticed that the Jenkins is now build to refer to @etsauer personal repo directly for the Library. So it of courses didn't include this PR.
The function itself works, we just need to fix the Jenkins-s2i not to refer to wrong location.

**Pull request merged**
