### PR TITLE
Added travisci build

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Added travis.yaml to build codebase

#### How do we test this?
Check travisci build output

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
DONT MERGE.

Needs:
- https://github.com/redhat-cop/pipeline-library/pull/46

**Comment by garethahealy** [comment]
Ready for review.

**Comment by garethahealy** [comment]
@pabrahamsson ; can you also enable travis please
- https://travis-ci.org/redhat-cop/pipeline-library

**Comment by pabrahamsson** [comment]
@garethahealy I currently don't have enough permissions to do this. I've requested the permissions and will enable as soon as I get them.

**Pull request merged**
